language: java
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk: oraclejdk9

install:
- wget --no-check-certificate https://github.com/forax/pro/archive/master.zip
- unzip pro-master.zip
- cd pro-master
- chmod u+x build.sh
- ./build.sh
- cd ..

script:
- echo ./pro-master/bin/pro
